# Generated by Django 4.2 on 2023-07-28 15:03

import auctions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='items',
            field=models.ForeignKey(default=auctions.models.Category.get_other_category_pk, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
