# Generated by Django 4.2 on 2023-07-29 14:44

import auctions.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_item_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ForeignKey(default=auctions.models.Category.get_other_category_pk, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auctions.category'),
        ),
    ]
