# Generated by Django 4.2 on 2023-05-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_bid_item_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='bid',
        ),
        migrations.AddField(
            model_name='item',
            name='starting_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
