# Generated by Django 4.2 on 2023-06-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_item_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='describtion',
            new_name='description',
        ),
    ]
