# Generated by Django 4.2 on 2023-07-13 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_watchlist_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='item_id',
            new_name='item',
        ),
    ]
