# Generated by Django 4.2 on 2023-07-20 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_rename_item_id_watchlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids_item', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
