# Generated by Django 4.2 on 2023-07-21 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_item_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
